### ISSUE TITLE
Class-level uri annotations

### ISSUE THREAD

**Issue by joeporpeglia** [erunion/mill#54]
Depending on code organization, uri annotations can become redundant when applied to every resource action. For example, a class that only defines the `GET` and `POST` actions for the `/todos` resource would end up using the same uri annotations for both methods. In those cases it could be cleaner to throw the annotation in the class's docblock.

**Comment by erunion** [comment]
Huh, interesting. I kind of like that idea.

**Comment by erunion** [comment]
Along this, it'd be nice if you no longer had to attach a URI to a URI segment when declaring it on a resource action.

It gets **really** repetitive if you have an action that's being served from multiple URIs to have to have the same segment docs *n* times.

**Comment by erunion** [comment]
```php
/**
 * @api-resource Pictures
 *
 * @api-uri:public {On Demand\Pages\Pictures} /ondemand/pages/+ondemand_id/pictures/#poster_id
 * @api-uriSegment {/ondemand/pages/+ondemand_id/pictures/#poster_id} ondemand_id (integer) - On Demand ID
 * @api-uriSegment {/ondemand/pages/+ondemand_id/pictures/#poster_id} poster_id (integer) - Picture ID
 *
 * @api-contentType application/vnd.vimeo.picture
 * @api-minVersion 3.1
 */
```

With this syntax, anything denoted within a docblock that has `@api-resource` will be applied to any docblock in that controller that contains an `@api-method` annotation. There will be no substitutions allowed, just a blanket "add this too".

It should accept any annotations that are the following:

* [ ] `@api-uri`
* [ ] `@api-uriSegment`
* [ ] `@api-contentType`
* [ ] `@api-minVersion`
* [ ] `@api-throws`

Anything not in that list found in the first docblock should throw a compilation error.
